### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by fxfactorial** [bagder/libbrotli#1]
Thanks for getting this rolling, I'm guessing you don't use OS X.

```
dyld: Symbol not found: _kBrotliDictionary
  Referenced from: /usr/local/lib/libbrotli.0.dylib
  Expected in: flat namespace
 in /usr/local/lib/libbrotli.0.dylib
[1]    54387 trace trap  ./main.native
```

**Comment by bagder** [comment]
True, I don't. So what exactly is the problem here? That symbol `kBrotliDictionary` is in dictionary.h (brrr, declaring static variables in a header file!) that is included by decode.c

**Comment by fxfactorial** [comment]
I'm trying to use it as a library for an mixed program with OCaml and I get this error, I looked with `nm` and see `U _kBrotliDictionary` which implies to me its not being linked in the `dylib`. 

I linked with `-lbrotli`

**Comment by bagder** [comment]
Hm, curious. On Linux I get this:

```
$ nm .libs/libbrotli.a | grep Dictionary
0000000000003a80 T BrotliSetCustomDictionary
0000000000001b00 r kBrotliDictionary
0000000000001a80 r kBrotliDictionaryOffsetsByLength
0000000000001a50 r kBrotliDictionarySizeBitsByLength
0000000000000000 t TransformDictionaryWord
```

**Comment by fxfactorial** [comment]
```
$ nm libbrotli.a | grep Dictionary
0000000000004140 T _BrotliSetCustomDictionary
0000000000003e80 t _TransformDictionaryWord
                                U _kBrotliDictionary
0000000000013860 s _kBrotliDictionaryOffsetsByLength
00000000000138d0 s _kBrotliDictionarySizeBitsByLength
```

**Comment by bagder** [comment]
Ok, I can repeat it on my mac too.

**Comment by bagder** [comment]
Blah, they changed the code overnight. My linux had a checkout from yesterday...

**Comment by fxfactorial** [comment]
Indeed, I suspect this will be a moving target for a little bit.

**Comment by fxfactorial** [comment]
Why don't you just make the brotli repo into a git submodule?

**Comment by bagder** [comment]
I guess I can, I was just aiming for being rather loosely coupled...
