### ISSUE TITLE
Encoder files missing

### ISSUE THREAD

**Issue by Lukasa** [bagder/libbrotli#12]
I copied your list of encoder/decoder files for [brotlipy](https://github.com/python-hyper/brotlipy). However, when I came to start wrapping the encoder in a C API I discovered some weird linkage errors. This turned out to be because there were some files in my checkout that you didn't have in your list of C++ files for the encoder. I suspect if you tried to load the encoder library you'd find that the library load would fail because of missing symbols.

I was specifically missing brotli/enc/dictionary.cc and brotli/enc/utf8_util.cc.

**Comment by bagder** [comment]
Thanks!
