### ISSUE TITLE
Decoder / encoder in one or two libs?

### ISSUE THREAD

**Issue by bagder** [bagder/libbrotli#2]
(continued from [here](https://github.com/google/brotli/issues/162#issuecomment-143108336))

Thinking about it one step further, It might perhaps make sense to keep two separate ones. That makes it smaller for the ones who need only decoding.

(In addition to the fact that the encoder is C++ while the decoder is plain C...)

**Comment by fxfactorial** [comment]
Ugh, I'm also annoyed that they have it half C++ and other C, I would have preferred straight C. How far can you get with just the decoder? That's just like unzipping correct?

**Comment by bagder** [comment]
Yeah, all the API functions for decoding are in the dec/ folder and the files we use right now to build libbrotli with. The decode.h file is also the docs for the decoding API.

**Comment by fxfactorial** [comment]
I'm going through it now and trying to use this function

``` c
BrotliResult BrotliDecompressBuffer(size_t encoded_size,
                                    const uint8_t* encoded_buffer,
                                    size_t* decoded_size,
                                    uint8_t* decoded_buffer);
```

But that usage of uint8_t\* is strange to me, its basically just going to write integers? Why is it this instead of a char *? do we just pass it a char \* and it allocates for us?..

**Comment by bagder** [comment]
It's more of a preference. They picked uint8_t instead of "unsigned char" but that has no real difference. They are in effect bytes. (I have no affiliation with the brotli team so I really cannot answer for them.)

**Comment by fxfactorial** [comment]
@bagder Can you tell me what I have to change in the configure.ac or what needed files to get the encoder as a lib, or even better to have both encoder and decoder as one lib? I kind of want to use the encoder code.

**Comment by bagder** [comment]
commit fc4df8a3dcf86 now builds those files too and put them into the lib. You need c++11 support in your compiler.

This breaks 'make install' right now since they have one header file each named streams.h in enc/ and dec/ and make install tries to put them into the same install directory...

**Comment by bagder** [comment]
I filed an issue over at brotli to get this discussed: https://github.com/google/brotli/issues/181

**Comment by fxfactorial** [comment]
Ah, yea I wish `make install` would work. Having two headers would be awkward.

**Comment by bagder** [comment]
A work-around could be to put them into brotli/enc and brotli/dec even on install but I wanted to avoid that.

**Comment by fxfactorial** [comment]
Yea, I was thinking that too. Is it possible to do that temporarily or on a branch? I kind of want to use the encoder (with the headers) (Sorry I would do this but the whole auto configure stack is foreign to me)

**Comment by bagder** [comment]
I pushed a work-around for now in commit 83f0bab163. We can go back to the previous approach later if the brotli team agrees with me...

**Comment by fxfactorial** [comment]
Much appreciated!
