### ISSUE TITLE
Failed to execute process './autogen.sh'

### ISSUE THREAD

**Issue by angristan** [bagder/libbrotli#23]
Hello, I have an error while executing autogen : 

```
root@pulse ~/libbrotli# ./autogen.sh
Failed to execute process './autogen.sh'. Reason:
exec: Exec format error
The file './autogen.sh' is marked as an executable but could not be run by the operating system.
```

**Comment by bagder** [comment]
how about `sh autogen.sh` instead?

**Comment by angristan** [comment]
Yes it works but I wonder why you did put "./" in the README ^^

**Comment by bagder** [comment]
because it is supposed to work like that too...

**Comment by angristan** [comment]
I tested on two Debian 8 servers, it doesn't work

**Comment by bagder** [comment]
But why? I tried it just now on a debian server of mine and it worked.

Can you show me what `ls -l autogen.sh` says for you?

**Comment by angristan** [comment]
```
root@pulse ~/libbrotli# ls -l autogen.sh
-rwxr-xr-x 1 root root 684 janv. 27 21:32 autogen.sh*
```

Found the solution : it was my shell (fish), it works with bash. Thanks
