### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by othree** [bagder/libbrotli#28]
Hi

I want to help ngx_brotli easier to install on OSX using homebrew.
But before I can do it.
I will need a release like [this](https://github.com/leev/ngx_http_geoip2_module/releases).

Is there any plan for a release?

Thanks

**Comment by bagder** [comment]
Okay! Then consider this a first release: https://github.com/bagder/libbrotli/releases/tag/libbrotli-1.0

**Comment by othree** [comment]
Thank you.
But unfortunately, brotli release 0.3.0 is still too old.
So I have to wait a new release of brotli ~

**Comment by bagder** [comment]
What do you mean? The libbrotli-1.0 tag was set on the current source tree which uses the current git master of brotli: v0.3.0-64-gcfba2db. That is 64 commits done after the 0.3.0 tag in their tree.

**Comment by othree** [comment]
I got this error message

```
make: *** No rule to make target `brotli/enc/compress_fragment.cc', needed by `brotli/enc/libbrotlienc_la-compress_fragment.lo'.  Stop.
```

And `enc/compress_fragment.cc` is not in their 0.3.0 release at https://github.com/google/brotli/releases

**Comment by bagder** [comment]
Again, we're not using the brotli 0.3.0 release. Aren't you using the git submodule from libbrotli?

**Comment by bagder** [comment]
I just tried

```
make distclean
./autogen.sh
./configure
make
```

... and it worked fine in my git checkout

**Comment by othree** [comment]
Yes, I know libbrotli dont use brotli 0.3.0 release.
I have tried use git submodule and works fine.
But homebrew only accepts stable package.
So I still have to wait brotli's next release.

Just want to let you know I can't submit libbrotli into homebrew right now.

**Comment by bagder** [comment]
Ah, sorry. Now I get it!

**Comment by othree** [comment]
No problem.

I will let you know when I complete send Formula to homebrew :smile:
