### ISSUE TITLE
Brotli 0.4.0 released

### ISSUE THREAD

**Issue by xetorixik** [bagder/libbrotli#32]
[Brotli 0.4.0 is released](https://github.com/google/brotli/releases/tag/v0.4.0).
Please update libbrotli with the latest upstream release, because it has exciting new features and options. 
The ["Adoption by brotli upstream?" issue](https://github.com/bagder/libbrotli/issues/29) ,is still open, hence my question.

**Comment by bagder** [comment]
done!

**Comment by xetorixik** [comment]
@bagder High five mate! great, thanks for the quick action and reaction.

**Comment by Behrouz-m** [comment]
Thanks for the library. 
I pulled this version but during make it says:
`make[1]: *** No rule to make target `brotli/enc/compressor.h', needed by `all-am'.  Stop.`

**Comment by bagder** [comment]
@ray-pixar: then I suggest you rerun `./autogen.sh` and `./configure` and try again!
