### ISSUE TITLE
stream encode library support

### ISSUE THREAD

**Issue by myraid** [bagder/libbrotli#33]
I see that the new version of the broli has support for stream encoding. What is the plan to have a library for stream encoding?

**Comment by bagder** [comment]
didn't it already?

upstream brotli changed to a plain C encoder so I figure we need to resync with that...

**Comment by myraid** [comment]
Oh ok. I was looking for BrotliCompressStream similar to BrotliDecompressStream and thought that the stream encoding is not supported. 
Looked through the code and found that stream compress is supported.  Closing the issue.
