### ISSUE TITLE
Permissions erros on Debian

### ISSUE THREAD

**Issue by fxfactorial** [bagder/libbrotli#4]
I'm trying this out on Debian Jessie and getting silly permissions errors on the final step of `make install`:

``` shell
/bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libbrotli.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libbrotli.so.0.0.0 /usr/local/lib/libbrotli.so.0.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libbrotli.so.0.0.0': Permission denied
```

**Comment by bagder** [comment]
Isn't that just because your user aren't allowed to write in /usr/local/\* which is the default prefix?

Fix this by either running `sudo make install` or by changing the prefix and install it somewhere else, with `./configure --prefix=$HOME/special-dir`

**Comment by fxfactorial** [comment]
Okay, so its most likely just my own fault. Thanks.

**Comment by fxfactorial** [comment]
Fixed permissions but now linking issues at run time.

`error while loading shared libraries: libbrotli.so.0: cannot open shared object file: No such file or directory`

My `ld.so.conf`

include /etc/ld.so.conf.d/*.conf
/usr/local/lib

**Comment by bagder** [comment]
Your ld.so.conf looks like that, but did you re-run ldconfig to make it "learn"?

**Comment by fxfactorial** [comment]
Ah! I thought it consulted the file before each usage, but I guess that would be a really stupid thing to do, rerunning ldconfig worked. Thanks!
