### ISSUE TITLE
libtool: warning: undefined symbols not allowed in i686-w64-mingw32 shared libraries; building static only

### ISSUE THREAD

**Issue by yyjdelete** [bagder/libbrotli#40]
Try to compile libbrotli in windows with `msys2` and `mingw32`
Then get the before during make, and no dlls is created.

Seems http://stackoverflow.com/a/22884787 is an workaround for me, but not sure if this should be added OS-independently.

**Comment by bagder** [comment]
In the curl project, we add that option if the $host_os matches `cygwin* | mingw* | pw32* | cegcc* | os2* | aix*`, I figure we should use the same.
