### ISSUE TITLE
Makefile:305: ../brotli/c/tools/.deps/brotli-brotli.Po: No such file or directory

### ISSUE THREAD

**Issue by chnypc** [bagder/libbrotli#45]
I have try to compile libbrotli on Centos 6, but it's getting error.

[root@centos-vhost libbrotli]# make
make  all-recursive
make[1]: Entering directory `/opt/libbrotli'
Making all in .
make[2]: Entering directory `/opt/libbrotli'
  CC     brotli/c/dec/libbrotlidec_la-bit_reader.lo
  CC     brotli/c/dec/libbrotlidec_la-decode.lo
  CC     brotli/c/dec/libbrotlidec_la-huffman.lo
  CC     brotli/c/dec/libbrotlidec_la-state.lo
  CC     brotli/c/common/libbrotlidec_la-dictionary.lo
  CCLD   libbrotlidec.la
  CC     brotli/c/enc/libbrotlienc_la-backward_references.lo
  CC     brotli/c/enc/libbrotlienc_la-histogram.lo
  CC     brotli/c/enc/libbrotlienc_la-block_splitter.lo
  CC     brotli/c/enc/libbrotlienc_la-literal_cost.lo
  CC     brotli/c/enc/libbrotlienc_la-brotli_bit_stream.lo
  CC     brotli/c/enc/libbrotlienc_la-metablock.lo
  CC     brotli/c/enc/libbrotlienc_la-encode.lo
  CC     brotli/c/enc/libbrotlienc_la-static_dict.lo
  CC     brotli/c/enc/libbrotlienc_la-entropy_encode.lo
  CC     brotli/c/common/libbrotlienc_la-dictionary.lo
  CC     brotli/c/enc/libbrotlienc_la-utf8_util.lo
  CC     brotli/c/enc/libbrotlienc_la-compress_fragment.lo
  CC     brotli/c/enc/libbrotlienc_la-compress_fragment_two_pass.lo
  CC     brotli/c/enc/libbrotlienc_la-memory.lo
  CC     brotli/c/enc/libbrotlienc_la-backward_references_hq.lo
  CC     brotli/c/enc/libbrotlienc_la-bit_cost.lo
  CC     brotli/c/enc/libbrotlienc_la-dictionary_hash.lo
  CC     brotli/c/enc/libbrotlienc_la-cluster.lo
  CCLD   libbrotlienc.la
make[2]: Leaving directory `/opt/libbrotli'
Making all in tools
make[2]: Entering directory `/opt/libbrotli/tools'
Makefile:305: ../brotli/c/tools/.deps/brotli-brotli.Po: No such file or directory
make[2]: *** No rule to make target `../brotli/c/tools/.deps/brotli-brotli.Po'.  Stop.
make[2]: Leaving directory `/opt/libbrotli/tools'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/libbrotli'
make: *** [all] Error 2
[root@centos-vhost libbrotli]# locate brotli-brotli.Po
/opt/libbrotli/tools/$(top_srcdir)/brotli/c/tools/.deps/brotli-brotli.Po
[root@centos-vhost libbrotli]# 

Do you have any idea about this issue?

**Comment by bagder** [comment]
This problem arrived with the recent change from #43 and the follow-up commit 5822e2b49b96482.

You can either revert those two commits or try this as a work-around (invoked in the source tree root):

    $ touch brotli/c/tools/.deps/brotli-brotli.Po
    $ make

**Comment by rcanavan** [comment]
I think this would be fixed with #46.
