### ISSUE TITLE
cc1plus: error: unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by nikhil791** [bagder/libbrotli#51]
Hi,

## **Output of "gcc --version"**
[root@datanode2 lib]# gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
 I have installed below package by yum:
devtoolset-2-gcc.x86_64                                         4.8.2-15.1.el6                 @slc6-devtoolset

## **Output of "yum info gcc":**
Installed Packages
Name        : gcc
Arch        : x86_64
Version     : 4.4.7
Release     : 18.el6
Size        : 19 M
Repo        : installed
From repo   : base
Summary     : Various compilers (C, C++, Objective-C, Java, ...)
URL         : http://gcc.gnu.org
License     : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions
Description : The gcc package contains the GNU Compiler Collection version 4.4.
            : You'll need this package in order to compile C code.

can anyone help me why I am getting this error. Default gcc package was gcc4.4.7. After that I installed gcc4.8.2 then also I am getting this error..

Any help would be appreciated..

**Comment by bagder** [comment]
How exactly do you get this problem with libbrotli? It is not using C++ nor does it try to use that option!
