### ISSUE TITLE
Separate encoder and decoder

### ISSUE THREAD

**Issue by rockdaboot** [bagder/libbrotli#8]
As Daniel already suggested somewhere (couldn't find it again), we should have two libraries. One for encoding and one for decoding. Because...
1. encoder is C++, decoder is C (would like to see encoder in C as well, sigh)
2. the library is quite large, splitting it up would decrease load time for some apps

And we should than have one tool for decoding and one for encoding.

**Comment by bagder** [comment]
Yeah, perhaps we should make them as brotlidec and brotlienc? Then the separate include directories also make more sense!

**Comment by khaledhosny** [comment]
Two different libraries make sense, not all applications require both functionalities (that is probably why the decoder is in C as it is what most application will want so it was made more portable).

**Comment by bagder** [comment]
As of commit 187f3a97e it is now split into two libs:

libbrotlienc is the encoder lib, does compression

libbrotlidec is the decoder lib, does decompression

Not married to the names, I just picked 'enc' and 'dec' from the names of the source dirs in the brotli repo.
