### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by rockdaboot** [bagder/libbrotli#9]
The current versioning of brotli is not clear to me.
There is a git tag 0.2.0, the draft having -05 and we have a define #define BROTLI_VERSION "0.1.0"

Maybe we could agree on something here.

**Comment by bagder** [comment]
It's just a start with no deeper thought given to it yet. Does brotli have a version number we can use and just add a libbrotli version/number to it or something?

**Comment by khaledhosny** [comment]
The `BROTLI_VERSION` should match the git tag until upstream provides one. The version of the draft is for the spec not the library.

**Comment by rockdaboot** [comment]
Ok, forget the draft.
BROTLI_VERSION could (should ?) be generated by ./configure together with MAJOR, MINOR and PATCH number. ./configure could get this information from a file and/or command, e.g. from 'git describe --tags'.
But that leads us to the point that this repo should be integrated directly into google/brotli !?
We should check with them if they would accept a autotools build env.
WDYT ?

**Comment by bagder** [comment]
I just presumed it isn't an accident they don't build a library of their own already, so I started this meta project to do it for all of us who prefer using libraries. But yes, ideally they should build a library themselves and no one would be happier if our effort here would help that happen. I'm not counting on that though.

Until that happen, let's do something useful!

**Comment by bagder** [comment]
So let's just keep configure.ac in sync manually for now. It says 0.1.0 as of @rockdaboot's patch just merged.
